services:
  mtgobot:
    image: videreproject/mtgosdk:headless
    container_name: mtgobot
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      # Disable MTGO GUI for bot execution
      - DISPLAY=:99
      # Suppress Wine debug noise.
      - WINEDEBUG=-all
      - TZ=America/Los_Angeles
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/bash
